title: Larisa Cof # your name (or website title) here
logo: "/images/ProfilePic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I am a 22-year-old woman passionated about exploring my future as an ICT engineer. <br>
  
  In August of 2021, I plan to attend the ICT Innovation Master's degree program, 
  Cloud and Network Infrastructures track at 
  KTH Royal Institute of Technology, where I am currently pursuing a
  bachelor's degree (graduating spring of 2021).
  <br><br>
  <br>
  <a href="https://www.linkedin.com/in/larisa-cof-b57925153/" target="_blank">LinkedIn</a> 
  <a href="https://www.kth.se/profile/larisac/" target="_blank">KTH Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
